
development:
 adapter: postgresql 
 database: sunraynotice_development 
 username: postgres
 password: sunray2012! 
 host: localhost
 port: 5432
 
test:
  adapter: postgresql 
  database: sunraynotice
  username: postgres
  password: root
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: sunraynotice_development
  username: postgres
  password: root
  host: localhost
  port: 5432